# Disparando errores dentro de una Función Generator.

Si un error es encontrado dentro de una función Generator, entonces el error será disparado por la llamada `next()` que de con este esrror. La llamada `next()` que llama el error retornará un valor undefined y los valores adicionales de la sentencia yield serán ignorados. Las llamadas subsecuentes a `next()` despues del error también retornarán `undefined`.

Note el efecto de disparar error por parte de una función Generator.

```js
function* funcGenerator(){
    yield 'a';
    yield 'b';
    throw new Error("error disparado por la funcion funcGenerator()")
    yield 'c';
    yield 'd';
}

var objGenerator = funcGenerator();

try {
    var a = objGenerator.next(); // { value: 'a', done: false }
    var b = objGenerator.next(); // { value: 'b', done: false }
    var c = objGenerator.next(); // undefined <- esta es la que dispara el error
    var d = objGenerator.next(); // undefined <- las otras llamadas a yield son ignoradas despues del error
}catch(e){
    console.log(e.message);
}
```


